### PR TITLE
feat: [STO-6893] added wiz icon

### PR DESCRIPTION
**Pull request by tkAcharya007**
You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- StyleLint: `retrigger stylelint`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- ImageSnapshot `retrigger ImageSnapshot`

### CODE REVIEW

**Comment by bot2-harness** [comment]
Image snapshots failed please check https://console.cloud.google.com/storage/browser/ui-team-bucket/uicore-2332

**Review by jsentongo — DISMISSED** [review]

**Comment by bot2-harness** [comment]
Image snapshots failed please check https://console.cloud.google.com/storage/browser/ui-team-bucket/uicore-2334

**Review by atmollo-harness — APPROVED** [review]

**Comment by atmollo-harness** [comment]
@tkAcharya007 Could you bump the version in the `packages/uicore/package.json` that version needs to be updated to build a new version of the package

**Comment by bot2-harness** [comment]
Image snapshots failed please check https://console.cloud.google.com/storage/browser/ui-team-bucket/uicore-2337

**Comment by bot2-harness** [comment]
Image snapshots failed please check https://console.cloud.google.com/storage/browser/ui-team-bucket/uicore-2338

**Review by atmollo-harness — APPROVED** [review]

**Review by jsentongo — APPROVED** [review]

**Pull request merged**
