### PR TITLE
feat: [PL-27457] : SplitButton should behave like normal button without children

### PR DESCRIPTION
**Pull request by pankajsingh-harness**
Jira: https://harness.atlassian.net/browse/PL-27457

Added condition to render "Popover" only when children's count is greater than zero.

Screenshot 2022-08-17 at 7 20 01 PM

---

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- StyleLint: `retrigger stylelint`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- ImageSnapshot `retrigger ImageSnapshot`

### CODE REVIEW

**Comment by pankajsingh-harness** [comment]
retrigger ImageSnapshot

**Comment by pankajsingh-harness** [comment]
retrigger ImageSnapshot

**Review by kapilkumawat86 — APPROVED** [review]

**Review by yc147 — COMMENTED** [review]
Why did `storyshots-puppeteer/__image_snapshots__/imageshot-tests-runner-ts-puppeteer-tests-components-multi-step-progress-indicator-multi-step-progress-indicator-comp-1-snap.png` change?

**Comment by pankajsingh-harness** [comment]
@yc147 
I ran the following:

-  yarn build-storybook
-  yarn puppeteer-storyshots

and these files generated

**Review by yc147 — COMMENTED** [review]
OK got it. Since ImageSnapshot check is not mandatory, so someone updated the other component without updating the snapshot.

**Review by udayvunnam — APPROVED** [review]

**Pull request merged**
