### PR TITLE
feat: [DBOPS-821]: Add icons for hover state on migration table

### PR DESCRIPTION
**Pull request by sarthak-setia**
Add icons for hover state on migration table 

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- StyleLint: `retrigger stylelint`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- ImageSnapshot `retrigger ImageSnapshot`

### CODE REVIEW

**Comment by bot2-harness** [comment]
Image snapshots failed please check https://console.cloud.google.com/storage/browser/ui-team-bucket/uicore-2924

**Comment by sarthak-setia** [comment]
retrigger stylelint

**Comment by sarthak-setia** [comment]
retrigger ImageSnapshot

**Comment by sarthak-setia** [comment]
retrigger jest

**Comment by sarthak-setia** [comment]
retrigger jest

**Review by avinashmadhwani02 — APPROVED** [review]

**Comment by bot2-harness** [comment]
Image snapshots failed please check https://console.cloud.google.com/storage/browser/ui-team-bucket/uicore-2934

**Review by sonaligoyal-harness — APPROVED** [review]

**Pull request merged**
