### PR TITLE
fix: [CODE-1249]: updated code icons for dark mode

### PR DESCRIPTION
**Pull request by rkapoor10**
## Summary. 

Update CODE nav icons to support dark mode - 

Icons added 
-  src/code-gear.svg
- src/code-pull.svg
- src/thinner-code-repos.svg
- src/thinner-code-webhook.svg

Icons Updated 
- src/code-commit.svg
- src/code-file.svg
- src/code-tag.svg

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- StyleLint: `retrigger stylelint`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- ImageSnapshot `retrigger ImageSnapshot`

### CODE REVIEW

**Comment by bot2-harness** [comment]
Image snapshots failed please check https://console.cloud.google.com/storage/browser/ui-team-bucket/uicore-2316

**Comment by bot2-harness** [comment]
Image snapshots failed please check https://console.cloud.google.com/storage/browser/ui-team-bucket/uicore-2319

**Review by cjlee01 — DISMISSED** [review]

**Comment by cjlee01** [comment]
You ran the icons thru svgo right ?

**Review by tan-nhu — APPROVED** [review]

**Comment by bot2-harness** [comment]
Image snapshots failed please check https://console.cloud.google.com/storage/browser/ui-team-bucket/uicore-2325

**Review by rajarshee-harness — APPROVED** [review]

**Review by karansaraswat19 — APPROVED** [review]

**Pull request merged**
