### PR TITLE
fix: updated fill of intelligence-flash to currentcolor

### PR DESCRIPTION
**Pull request by harish-viswa**
You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- StyleLint: `retrigger stylelint`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- ImageSnapshot `retrigger ImageSnapshot`

### CODE REVIEW

**Comment by bot2-harness** [comment]
Image snapshots failed please check https://console.cloud.google.com/storage/browser/ui-team-bucket/uicore-2486

**Review by shaurya-harness — DISMISSED** [review]

**Comment by bot2-harness** [comment]
Image snapshots failed please check https://console.cloud.google.com/storage/browser/ui-team-bucket/uicore-2487

**Review by shaurya-harness — APPROVED** [review]

**Review by namanharness — APPROVED** [review]

**Comment by harish-viswa** [comment]
retrigger typecheck

**Comment by harish-viswa** [comment]
retrigger typecheck

**Comment by harish-viswa** [comment]
retrigger typecheck

**Pull request merged**
