### PR TITLE
feat: [AH-8]: Add new icons required for HAR (Harness Artifact Registry) module

### PR DESCRIPTION
**Pull request by shivanand-harness**
You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- StyleLint: `retrigger stylelint`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- ImageSnapshot `retrigger ImageSnapshot`

### CODE REVIEW

**Comment by bot2-harness** [comment]
Image snapshots failed please check https://console.cloud.google.com/storage/browser/ui-team-bucket/uicore-2460

**Comment by shivanand-harness** [comment]
retrigger titlecheck

**Review by pankajsingh-harness — CHANGES_REQUESTED** [review]
Check for already added icons. Seems there is repeated icons added

**Comment by avinashmadhwani02** [comment]
@shivanand-harness use this tool to reduce size of icons - https://jakearchibald.github.io/svgomg/
Also, use currentColor instead of hardcoded color

**Comment by bot2-harness** [comment]
Image snapshots failed please check https://console.cloud.google.com/storage/browser/ui-team-bucket/uicore-2461

**Review by pankajsingh-harness — APPROVED** [review]

**Comment by bot2-harness** [comment]
Image snapshots failed please check https://console.cloud.google.com/storage/browser/ui-team-bucket/uicore-2463

**Review by litvinovstas — APPROVED** [review]

**Pull request merged**
