### PR TITLE
chore: [CDS-102718]: Add GCR prepare rollback step

### PR DESCRIPTION
**Pull request by sonaligoyal-harness**
You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- StyleLint: `retrigger stylelint`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- ImageSnapshot `retrigger ImageSnapshot`

### CODE REVIEW

**Review by litvinovstas — APPROVED** [review]

**Comment by sonaligoyal-harness** [comment]
retrigger titlecheck

**Comment by sonaligoyal-harness** [comment]
retrigger jest

**Review by litvinovstas — CHANGES_REQUESTED** [review]
checks

**Comment by sonaligoyal-harness** [comment]
retrigger eslint

**Comment by bot2-harness** [comment]
Image snapshots failed please check https://console.cloud.google.com/storage/browser/ui-team-bucket/uicore-2841

**Review by litvinovstas — APPROVED** [review]

**Review by MondalSayantan — APPROVED** [review]

**Pull request merged**
