### PR TITLE
fix: [CDS-56486]: number label not converting to string in selected I…

### PR DESCRIPTION
**Pull request by vikrant-harness**
…tem renderer

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- StyleLint: `retrigger stylelint`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- ImageSnapshot `retrigger ImageSnapshot`

### CODE REVIEW

**Comment by AnshuH** [comment]
retrigger build

**Comment by AnshuH** [comment]
retrigger eslint

**Review by chetanvekariya-harness — APPROVED** [review]

**Comment by vikrant-harness** [comment]
retrigger prettier

**Comment by vikrant-harness** [comment]
retrigger titlecheck

**Review by vkbansal-harness — APPROVED** [review]

**Review by AshwinBhatkal-Harness — APPROVED** [review]

**Comment by vikrant-harness** [comment]
retrigger jest

**Comment by vikrant-harness** [comment]
retrigger stylelint

**Comment by vikrant-harness** [comment]
retrigger typecheck

**Pull request merged**
