### PR TITLE
fix: [IDP-4222]: Added IDP Homepage Icons

### PR DESCRIPTION
**Pull request by samriddhi-daga**
You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- StyleLint: `retrigger stylelint`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- ImageSnapshot `retrigger ImageSnapshot`

### CODE REVIEW

**Comment by samriddhi-daga** [comment]
retrigger jest

**Comment by bot2-harness** [comment]
Image snapshots failed please check https://console.cloud.google.com/storage/browser/ui-team-bucket/uicore-2853

**Review by jenil-harness — APPROVED** [review]
LGTM

**Comment by bot2-harness** [comment]
Image snapshots failed please check https://console.cloud.google.com/storage/browser/ui-team-bucket/uicore-2855

**Review by agnivabanerjeeharness — APPROVED** [review]

**Pull request merged**
