### PR TITLE
feat: [PIE-6828]: Stale cache icon added

### PR DESCRIPTION
**Pull request by bhavya-sinha**
You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- StyleLint: `retrigger stylelint`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- ImageSnapshot `retrigger ImageSnapshot`

### CODE REVIEW

**Comment by bhavya-sinha** [comment]
retrigger ImageSnapshot

**Comment by bhavya-sinha** [comment]
retrigger ImageSnapshot

**Comment by bhavya-sinha** [comment]
retrigger titlecheck

**Review by satyam-harness — APPROVED** [review]

**Comment by bhavya-sinha** [comment]
retrigger titlecheck

**Pull request closed without merging**
