### PR TITLE
fix: [CDS-102868]: add checked property to radio input along with def…

### PR DESCRIPTION
**Pull request by abhishekbaneharness**
You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- StyleLint: `retrigger stylelint`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- ImageSnapshot `retrigger ImageSnapshot`

### CODE REVIEW

**Comment by abhishekbaneharness** [comment]
retrigger jest

**Comment by bot2-harness** [comment]
Image snapshots failed please check https://console.cloud.google.com/storage/browser/ui-team-bucket/uicore-2745

**Review by shivanand-harness — DISMISSED** [review]

**Comment by shivanand-harness** [comment]
@abhishekbaneharness update the version in package.json for uicore package

**Review by praneshg239 — DISMISSED** [review]

**Comment by abhishekbaneharness** [comment]
retrigger jest

**Comment by bot2-harness** [comment]
Image snapshots failed please check https://console.cloud.google.com/storage/browser/ui-team-bucket/uicore-2747

**Comment by abhishekbaneharness** [comment]
created a new pr, https://github.com/harness/uicore/pull/1435 with proper task id

**Comment by bot2-harness** [comment]
Image snapshots failed please check https://console.cloud.google.com/storage/browser/ui-team-bucket/uicore-2749

**Pull request closed without merging**
