### PR TITLE
feat: [PL-43477]: added icon for "certificates"

### PR DESCRIPTION
**Pull request by mayankVermaHarness**
You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- StyleLint: `retrigger stylelint`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- ImageSnapshot `retrigger ImageSnapshot`

### CODE REVIEW

**Review by namanharness — DISMISSED** [review]

**Comment by bot2-harness** [comment]
Image snapshots failed please check https://console.cloud.google.com/storage/browser/ui-team-bucket/uicore-2327

**Review by sunnykesh-harness — COMMENTED** [review]
Width hight is hard coded which is against : https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/1963262066/SVG+Guidelines+Best+Practices

**Comment by mayankVermaHarness** [comment]
> Width hight is hard coded which is against : https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/1963262066/SVG+Guidelines+Best+Practices

Good Catch! Thanks, I have updated it now.

**Comment by bot2-harness** [comment]
Image snapshots failed please check https://console.cloud.google.com/storage/browser/ui-team-bucket/uicore-2328

**Review by namanharness — APPROVED** [review]

**Review by sunnykesh-harness — APPROVED** [review]

**Pull request merged**
