### PR TITLE
fix: Adding adr and bugsnag icons

### PR DESCRIPTION
**Pull request by ajinkya-harness**
You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- StyleLint: `retrigger stylelint`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- ImageSnapshot `retrigger ImageSnapshot`
service-adr
service-name-bugsnag

### CODE REVIEW

**Comment by bot2-harness** [comment]
Image snapshots failed please check https://console.cloud.google.com/storage/browser/ui-team-bucket/uicore-2535

**Comment by bot2-harness** [comment]
Image snapshots failed please check https://console.cloud.google.com/storage/browser/ui-team-bucket/uicore-2536

**Review by bhavya-sinha — CHANGES_REQUESTED** [review]
Version bump?

**Comment by bhavya-sinha** [comment]
You didn't do yarn icons?

**Comment by bot2-harness** [comment]
Image snapshots failed please check https://console.cloud.google.com/storage/browser/ui-team-bucket/uicore-2537

**Comment by bot2-harness** [comment]
Image snapshots failed please check https://console.cloud.google.com/storage/browser/ui-team-bucket/uicore-2540

**Review by bhavya-sinha — APPROVED** [review]
LGTM

**Review by samriddhi-daga — APPROVED** [review]

**Pull request merged**
