### PR TITLE
feat: [IR-419]: Update icons for Incident Response

### PR DESCRIPTION
**Pull request by NickLanam**
These are the currently-final icons that Incident Response intends to use.
This is similar to [the last PR about this](https://github.com/harness/uicore/pull/1413), in that this product is not generally available yet and is changing by the day.

In use, the new icons look like this:
image

<details>
<summary>
You can use the following comments to re-trigger PR Checks
</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- StyleLint: `retrigger stylelint`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- ImageSnapshot `retrigger ImageSnapshot`

</details>

### CODE REVIEW

**Comment by bot2-harness** [comment]
Image snapshots failed please check https://console.cloud.google.com/storage/browser/ui-team-bucket/uicore-2713

**Review by abhinavrastogi-harness — APPROVED** [review]
hope we are following all the svg best practices noted here https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/1963262066/SVG+Guidelines+Best+Practices

**Comment by bot2-harness** [comment]
Image snapshots failed please check https://console.cloud.google.com/storage/browser/ui-team-bucket/uicore-2716

**Comment by NickLanam** [comment]
> hope we are following all the svg best practices noted here https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/1963262066/SVG+Guidelines+Best+Practices

A couple of them still had width and height specified from when I exported them from Figma, or wonky indentation, so I manually fixed them up just now. Some kept the `fill="none"` on purpose, as those ones are painted with strokes instead and thus removing that attribute would break the image entirely.

**Review by abhinavrastogi-harness — APPROVED** [review]

**Review by piis3 — APPROVED** [review]

**Pull request merged**
