### PR TITLE
feat: [IRO-310]: Add IR icons for side nav

### PR DESCRIPTION
**Pull request by NickLanam**
Adds icons to be used in sidebar navigation for Incident Response.
Some of these already exist under other names, but with different dimensions and fill colors that won't work with the side nav. For those, they've been duplicated and updated to be square and use `currentColor` so as not to disrupt users of the original version.

This will be used by https://github.com/harness/harness-core-ui/pull/22334

<details>

<summary>You can use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- StyleLint: `retrigger stylelint`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- ImageSnapshot `retrigger ImageSnapshot`

</details>

### CODE REVIEW

**Comment by bot2-harness** [comment]
Image snapshots failed please check https://console.cloud.google.com/storage/browser/ui-team-bucket/uicore-2706

**Comment by bot2-harness** [comment]
Image snapshots failed please check https://console.cloud.google.com/storage/browser/ui-team-bucket/uicore-2707

**Comment by bot2-harness** [comment]
Image snapshots failed please check https://console.cloud.google.com/storage/browser/ui-team-bucket/uicore-2708

**Review by SahilKr24 — APPROVED** [review]

**Comment by bot2-harness** [comment]
Image snapshots failed please check https://console.cloud.google.com/storage/browser/ui-team-bucket/uicore-2709

**Review by abhinavrastogi-harness — APPROVED** [review]

**Pull request merged**
